# /// script
# [tool.marimo.runtime]
# auto_instantiate = false
# on_cell_change = "lazy"
# ///

import marimo

__generated_with = "0.19.9"
app = marimo.App(app_title="Neural ODE BPTT (Torch)", auto_download=["html"])


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Neural ODE Training with Backpropagation Through Time (PyTorch)

    This notebook converts `week_4/scripts/torch/NODE_BPTT_vanilla.py` and
    `week_4/scripts/torch/NODE_BPTT_tuned.py` into one interactive app.

    **Design goal:** start from the **vanilla** setup, then progressively enable tuning options.

    **Navigation:** [Jump to Control Panel](#control-panel)
    """)
    return


@app.cell(hide_code=True)
def _():
    import marimo as mo
    import matplotlib.pyplot as plt
    import numpy as np
    import torch
    import torch.nn as nn

    return mo, nn, np, plt, torch


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ---
    ## 1. Continuous-Time Model and BPTT Objective

    True system:

    $$x(t)=\begin{bmatrix}u(t)\\v(t)\end{bmatrix}, \quad
    \dot{u}=v, \quad
    \dot{v}=-\beta v - \frac{g}{\ell}\sin(u).$$

    Learned NODE:

    $$\dot{x}=f_\theta(x), \qquad
    x_{k+1}=\Phi_\theta(x_k,\Delta t).$$

    Observations are generated by simulating the true dynamics and adding noise:

    $$x^{\mathrm{obs}}_{k,m}=x^{\mathrm{true}}_{k,m}+\eta_{k,m}.$$

    Training objective:

    $$\mathcal{L}(\theta)=\frac{1}{NM}\sum_{k,m}\|x^{\mathrm{sim}}_{k,m}-x^{\mathrm{obs}}_{k,m}\|_2^2 + \lambda\,\mathcal{R}(\theta).$$

    Optional regularization (tuned mode):

    $$\mathcal{R}(\theta)=\frac{1}{\operatorname{mean}\|f_\theta(x)\|_2+\varepsilon}.$$

    Optional normalization used in the tuned script:

    $$\tilde{x}=\frac{x-\mu_{\mathrm{obs}}}{\sigma_{\mathrm{obs}}+\varepsilon}.$$

    BPTT differentiates through all RK4 steps. In discrete adjoint form:

    $$a_k = a_{k+1}\frac{\partial \Phi_\theta}{\partial x_k} + \frac{\partial \ell_k}{\partial x_k},
    \qquad
    \nabla_\theta \mathcal{L}=\sum_k a_{k+1}\frac{\partial \Phi_\theta}{\partial \theta}.$$
    """)
    return


@app.cell(hide_code=True)
def _(nn, torch):
    def sample_ic(n_traj, device):
        u0 = 0.5 * (2 * torch.rand(n_traj, device=device) - 1)
        v0 = 0.5 * (2 * torch.rand(n_traj, device=device) - 1)
        return torch.stack([u0, v0], dim=-1)

    def pendulum_rhs(x, beta, ell, g):
        u, v = x[..., 0], x[..., 1]
        du = v
        dv = -beta * v - (g / ell) * torch.sin(u)
        return torch.stack([du, dv], dim=-1)

    def rk4_integrate(f, x0, t):
        n_steps = t.shape[0]
        xs = [x0]
        xk = x0
        for k in range(n_steps - 1):
            dt = t[k + 1] - t[k]
            k1 = f(xk)
            k2 = f(xk + 0.5 * dt * k1)
            k3 = f(xk + 0.5 * dt * k2)
            k4 = f(xk + dt * k3)
            xk = xk + (dt / 6.0) * (k1 + 2 * k2 + 2 * k3 + k4)
            xs.append(xk)
        return torch.stack(xs, dim=0)

    class NeuralODE(nn.Module):
        def __init__(self, hidden_dim=64, he_init=False, device="cpu"):
            super().__init__()
            self.net = nn.Sequential(
                nn.Linear(2, hidden_dim),
                nn.ReLU(),
                nn.Linear(hidden_dim, hidden_dim),
                nn.ReLU(),
                nn.Linear(hidden_dim, 2),
            ).to(device)
            if he_init:
                for module in self.net:
                    if isinstance(module, nn.Linear):
                        nn.init.kaiming_normal_(module.weight, mode="fan_in", nonlinearity="relu")
                        if module.bias is not None:
                            nn.init.constant_(module.bias, 0.0)

        def forward(self, x0, t):
            return rk4_integrate(lambda x: self.net(x), x0, t)

    return NeuralODE, pendulum_rhs, rk4_integrate, sample_ic


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### 1.1 Code: Loss Terms and Training Update

    The next cell implements:

    $$\mathcal{L}_{\mathrm{data}}=\frac{1}{NM}\sum_{k,m}\|x^{\mathrm{sim}}_{k,m}-x^{\mathrm{obs}}_{k,m}\|_2^2,$$

    $$\mathcal{L}=\mathcal{L}_{\mathrm{data}}+\lambda\mathcal{R},$$

    $$\theta \leftarrow \theta - \alpha \nabla_\theta \mathcal{L},$$

    with optional weight decay, gradient clipping, and plateau LR scheduling.
    """)
    return


@app.cell(hide_code=True)
def _(NeuralODE, mo, nn, np, pendulum_rhs, rk4_integrate, sample_ic, torch):
    @mo.persistent_cache
    def train_model(
        seed,
        g_true,
        beta_true,
        ell_true,
        t_final,
        n_steps,
        n_traj,
        noise_std,
        hidden_dim,
        use_he_init,
        epochs,
        lr,
        use_data_normalization,
        use_regularization,
        reg_strength,
        use_weight_decay,
        weight_decay,
        use_scheduler,
        scheduler_factor,
        scheduler_patience,
        use_grad_clip,
        clip_norm,
        print_every,
        device_type,
    ):
        torch.manual_seed(seed)
        device = torch.device(device_type)
        t_grid = torch.linspace(0.0, t_final, n_steps, device=device)

        x0_batch = sample_ic(n_traj, device)
        with torch.no_grad():
            x_true = rk4_integrate(
                lambda x: pendulum_rhs(x, beta_true, ell_true, g_true),
                x0_batch,
                t_grid,
            )
        x_obs = (x_true + noise_std * torch.randn_like(x_true)).detach()

        if use_data_normalization:
            x_obs_mean = x_obs.mean(dim=[0, 1], keepdim=True)
            x_obs_std = x_obs.std(dim=[0, 1], keepdim=True) + 1e-6
            x0_train = (x0_batch - x_obs_mean[0]) / x_obs_std[0]
        else:
            x_obs_mean = torch.zeros((1, 1, 2), device=device, dtype=x_obs.dtype)
            x_obs_std = torch.ones((1, 1, 2), device=device, dtype=x_obs.dtype)
            x0_train = x0_batch

        model = NeuralODE(hidden_dim=hidden_dim, he_init=use_he_init, device=device).to(device)
        wd = weight_decay if use_weight_decay else 0.0
        optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=wd)
        scheduler = None
        if use_scheduler:
            try:
                scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
                    optimizer,
                    mode="min",
                    factor=scheduler_factor,
                    patience=scheduler_patience,
                    verbose=True,
                )
            except TypeError:
                scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
                    optimizer,
                    mode="min",
                    factor=scheduler_factor,
                    patience=scheduler_patience,
                )

        mse = nn.MSELoss()
        total_history = []
        mse_history = []
        reg_history = []
        deriv_history = []
        lr_history = []

        for epoch in range(epochs):
            optimizer.zero_grad()

            x_sim = model(x0_train, t_grid)
            x_sim_rescaled = x_sim * x_obs_std + x_obs_mean
            mse_loss = mse(x_sim_rescaled, x_obs)

            if use_regularization:
                deriv_norm = torch.mean(torch.norm(model.net(x_sim), dim=-1))
                reg_term = reg_strength * (1.0 / (deriv_norm + 1e-6))
            else:
                deriv_norm = torch.tensor(float("nan"), device=device)
                reg_term = torch.tensor(0.0, device=device)

            loss = mse_loss + reg_term
            if not torch.isfinite(loss):
                print(f"[{epoch:04d}] non-finite loss; stopping early")
                break

            loss.backward()
            if use_grad_clip:
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=clip_norm)
            optimizer.step()
            if scheduler is not None:
                scheduler.step(mse_loss.detach())

            current_lr = optimizer.param_groups[0]["lr"]
            total_history.append(float(loss.item()))
            mse_history.append(float(mse_loss.item()))
            reg_history.append(float(reg_term.item()))
            deriv_history.append(float(deriv_norm.item()) if use_regularization else np.nan)
            lr_history.append(float(current_lr))

            if epoch % print_every == 0:
                print(
                    f"[{epoch:04d}] total={loss.item():.6f} "
                    f"mse={mse_loss.item():.6f} reg={reg_term.item():.6f} "
                    f"lr={current_lr:.6f}"
                )

        with torch.no_grad():
            x_fit = model(x0_train, t_grid)
            x_fit = x_fit * x_obs_std + x_obs_mean
            final_clean_mse = mse(x_fit, x_true).item()

        return {
            "t_grid": t_grid.detach().cpu().numpy(),
            "x_true": x_true.detach().cpu().numpy(),
            "x_obs": x_obs.detach().cpu().numpy(),
            "x_fit": x_fit.detach().cpu().numpy(),
            "total_history": np.asarray(total_history),
            "mse_history": np.asarray(mse_history),
            "reg_history": np.asarray(reg_history),
            "deriv_history": np.asarray(deriv_history),
            "lr_history": np.asarray(lr_history),
            "final_clean_mse": float(final_clean_mse),
        }

    return (train_model,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    <a id="control-panel"></a>
    ## 3. Control Panel

    **Vanilla baseline (default):**
    - Keep `Use regularization term` **off**.
    - Keep data normalization, weight decay, LR scheduler, and gradient clipping **off**.
    - Use `hidden_dim=64`, `lr=5e-2`, `epochs=501`.

    **How to tune toward the tuned setup:**
    1. Turn on **Use regularization term** and start with `reg_strength = 0.01`.
    2. If trajectories become overly flat, increase `reg_strength`; if training destabilizes, decrease it.
    3. Then optionally turn on normalization, He initialization, weight decay (`1e-4`), scheduler, and clipping.
    4. Reduce learning rate (`1e-2` or `5e-3`) if oscillatory; increase epochs if still improving.
    """)
    return


@app.cell(hide_code=True)
def _(mo, torch):
    seed_num = mo.ui.number(value=0, label="Seed")

    g_slider = mo.ui.slider(5.0, 15.0, value=9.81, step=0.01, label="Gravity g")
    beta_slider = mo.ui.slider(0.05, 1.0, value=0.25, step=0.01, label="Damping beta")
    ell_slider = mo.ui.slider(0.3, 2.0, value=0.9, step=0.01, label="Length ell")

    t_final_slider = mo.ui.slider(1.0, 10.0, value=5.0, step=0.5, label="Final time T")
    n_steps_slider = mo.ui.slider(50, 500, value=200, step=10, label="Time steps N")
    n_traj_slider = mo.ui.slider(4, 128, value=32, step=4, label="Trajectories M")
    noise_slider = mo.ui.slider(0.0, 0.1, value=0.01, step=0.005, label="Observation noise")

    hidden_dim_slider = mo.ui.slider(16, 256, value=64, step=16, label="Hidden dimension")
    use_he_init = mo.ui.checkbox(label="Use He initialization", value=False)

    epochs_dropdown = mo.ui.dropdown(
        {"501 (vanilla)": 501, "1000": 1000, "2000": 2000, "3000": 3000},
        value="501 (vanilla)",
        label="Epochs",
    )
    lr_dropdown = mo.ui.dropdown(
        {"5e-2 (vanilla)": 5e-2, "1e-2": 1e-2, "5e-3": 5e-3, "1e-3": 1e-3},
        value="5e-2 (vanilla)",
        label="Learning rate",
    )
    print_every_slider = mo.ui.slider(10, 500, value=100, step=10, label="Print every")

    use_regularization = mo.ui.checkbox(label="Use regularization term", value=False)
    reg_strength_slider = mo.ui.slider(0.0, 0.2, value=0.01, step=0.001, label="Regularization strength lambda")

    use_norm = mo.ui.checkbox(label="Use data normalization", value=False)
    use_weight_decay = mo.ui.checkbox(label="Use weight decay", value=False)
    weight_decay_dropdown = mo.ui.dropdown(
        {"1e-5": 1e-5, "1e-4": 1e-4, "1e-3": 1e-3},
        value="1e-4",
        label="Weight decay",
    )

    use_scheduler = mo.ui.checkbox(label="Use ReduceLROnPlateau", value=False)
    scheduler_factor_slider = mo.ui.slider(0.1, 0.9, value=0.5, step=0.1, label="Scheduler factor")
    scheduler_patience_slider = mo.ui.slider(10, 300, value=100, step=10, label="Scheduler patience")

    use_grad_clip = mo.ui.checkbox(label="Use gradient clipping", value=False)
    clip_norm_slider = mo.ui.slider(0.1, 5.0, value=1.0, step=0.1, label="Clip norm")

    plot_count_slider = mo.ui.slider(1, 8, value=3, step=1, label="Trajectories to plot")

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    train_button = mo.ui.run_button(label="Train Torch BPTT NODE")

    control_panel = mo.vstack(
        [
            train_button,
            mo.md(f"**Device:** `{device}`"),
            mo.md("### Physics"),
            g_slider,
            beta_slider,
            ell_slider,
            mo.md("### Data Generation"),
            seed_num,
            t_final_slider,
            n_steps_slider,
            n_traj_slider,
            noise_slider,
            mo.md("### Model"),
            hidden_dim_slider,
            use_he_init,
            mo.md("### Training"),
            epochs_dropdown,
            lr_dropdown,
            print_every_slider,
            mo.md("### Regularization"),
            use_regularization,
            reg_strength_slider,
            mo.md("### Optional Stabilization"),
            use_norm,
            use_weight_decay,
            weight_decay_dropdown,
            use_scheduler,
            scheduler_factor_slider,
            scheduler_patience_slider,
            use_grad_clip,
            clip_norm_slider,
            mo.md("### Visualization"),
            plot_count_slider,
        ]
    )

    control_panel
    return (
        beta_slider,
        clip_norm_slider,
        device,
        ell_slider,
        epochs_dropdown,
        g_slider,
        hidden_dim_slider,
        lr_dropdown,
        n_steps_slider,
        n_traj_slider,
        noise_slider,
        plot_count_slider,
        print_every_slider,
        reg_strength_slider,
        scheduler_factor_slider,
        scheduler_patience_slider,
        seed_num,
        t_final_slider,
        train_button,
        use_grad_clip,
        use_he_init,
        use_norm,
        use_regularization,
        use_scheduler,
        use_weight_decay,
        weight_decay_dropdown,
    )


@app.cell(hide_code=True)
def _(
    beta_slider,
    clip_norm_slider,
    device,
    ell_slider,
    epochs_dropdown,
    g_slider,
    hidden_dim_slider,
    lr_dropdown,
    mo,
    n_steps_slider,
    n_traj_slider,
    noise_slider,
    print_every_slider,
    reg_strength_slider,
    scheduler_factor_slider,
    scheduler_patience_slider,
    seed_num,
    t_final_slider,
    train_button,
    train_model,
    use_grad_clip,
    use_he_init,
    use_norm,
    use_regularization,
    use_scheduler,
    use_weight_decay,
    weight_decay_dropdown,
):
    mo.stop(not train_button.value, mo.md("_Click **Train Torch BPTT NODE** to start training._"))

    results = train_model(
        seed=int(seed_num.value),
        g_true=float(g_slider.value),
        beta_true=float(beta_slider.value),
        ell_true=float(ell_slider.value),
        t_final=float(t_final_slider.value),
        n_steps=int(n_steps_slider.value),
        n_traj=int(n_traj_slider.value),
        noise_std=float(noise_slider.value),
        hidden_dim=int(hidden_dim_slider.value),
        use_he_init=bool(use_he_init.value),
        epochs=int(epochs_dropdown.value),
        lr=float(lr_dropdown.value),
        use_data_normalization=bool(use_norm.value),
        use_regularization=bool(use_regularization.value),
        reg_strength=float(reg_strength_slider.value),
        use_weight_decay=bool(use_weight_decay.value),
        weight_decay=float(weight_decay_dropdown.value),
        use_scheduler=bool(use_scheduler.value),
        scheduler_factor=float(scheduler_factor_slider.value),
        scheduler_patience=int(scheduler_patience_slider.value),
        use_grad_clip=bool(use_grad_clip.value),
        clip_norm=float(clip_norm_slider.value),
        print_every=int(print_every_slider.value),
        device_type=device.type,
    )
    return (results,)


@app.cell(hide_code=True)
def _(mo):
    mo.md("""
    ---
    ## 4. Results
    """)
    return


@app.cell(hide_code=True)
def _(mo, results, use_regularization):
    n_epochs = int(results["total_history"].shape[0])
    final_total = float(results["total_history"][-1]) if n_epochs > 0 else float("nan")
    final_mse = float(results["mse_history"][-1]) if n_epochs > 0 else float("nan")
    final_reg = float(results["reg_history"][-1]) if n_epochs > 0 else 0.0
    final_clean_mse = float(results["final_clean_mse"])
    reg_mode = "on" if bool(use_regularization.value) else "off"

    mo.md(
        f"""
        **Training summary**

        - Epochs completed: `{n_epochs}`
        - Final total loss: `{final_total:.6e}`
        - Final data MSE loss: `{final_mse:.6e}`
        - Final regularization term: `{final_reg:.6e}` (regularization {reg_mode})
        - Final clean MSE against noise-free trajectories: `{final_clean_mse:.6e}`
        """
    )
    return


@app.cell(hide_code=True)
def _(np, plot_count_slider, plt, results):
    def _():
        t = results["t_grid"]
        x_true = results["x_true"]
        x_fit = results["x_fit"]

        n_plot = min(int(plot_count_slider.value), x_true.shape[1])
        idx = np.arange(n_plot)

        fig, axes = plt.subplots(3, n_plot, figsize=(5 * n_plot, 11), sharex=True, squeeze=False)
        for i, k in enumerate(idx):
            axes[0, i].plot(t, x_true[:, k, 0], "b-", label="True angle")
            axes[0, i].plot(t, x_fit[:, k, 0], "r--", label="NODE angle")
            axes[0, i].set_ylabel("u(t)")
            axes[0, i].set_title(f"Trajectory {k + 1}: angle")
            axes[0, i].grid(True, alpha=0.3)
            axes[0, i].legend()

            axes[1, i].plot(t, x_true[:, k, 1], "b-", label="True velocity")
            axes[1, i].plot(t, x_fit[:, k, 1], "r--", label="NODE velocity")
            axes[1, i].set_ylabel("v(t)")
            axes[1, i].set_title(f"Trajectory {k + 1}: velocity")
            axes[1, i].grid(True, alpha=0.3)
            axes[1, i].legend()

            err_u = x_fit[:, k, 0] - x_true[:, k, 0]
            err_v = x_fit[:, k, 1] - x_true[:, k, 1]
            axes[2, i].plot(t, err_u, "m-", label="u error")
            axes[2, i].plot(t, err_v, "g--", label="v error")
            axes[2, i].axhline(0.0, color="k", linewidth=1.0, alpha=0.5)
            axes[2, i].set_xlabel("Time")
            axes[2, i].set_ylabel("Error")
            axes[2, i].set_title(f"Trajectory {k + 1}: state error")
            axes[2, i].grid(True, alpha=0.3)
            axes[2, i].legend()

        plt.tight_layout()
        return fig


    _()
    return


@app.cell(hide_code=True)
def _(np, plt, results):
    def _():
        total_hist = results["total_history"]
        mse_hist = results["mse_history"]
        reg_hist = results["reg_history"]
        lr_hist = results["lr_history"]

        fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))

        epochs = np.arange(1, len(total_hist) + 1)
        axes[0].plot(epochs, total_hist, label="Total loss", color="tab:blue")
        axes[0].plot(epochs, mse_hist, label="MSE loss", color="tab:orange")
        axes[0].plot(epochs, reg_hist, label="Reg term", color="tab:green")
        axes[0].set_yscale("log")
        axes[0].set_xlabel("Epoch")
        axes[0].set_ylabel("Loss")
        axes[0].set_title("Loss curves")
        axes[0].grid(True, alpha=0.3)
        axes[0].legend()

        axes[1].plot(epochs, lr_hist, color="tab:red")
        axes[1].set_xlabel("Epoch")
        axes[1].set_ylabel("Learning rate")
        axes[1].set_title("Learning rate schedule")
        axes[1].grid(True, alpha=0.3)

        plt.tight_layout()
        return fig


    _()
    return


if __name__ == "__main__":
    app.run()
